/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author kevin
 */
public class ColaVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cola
     */
    public ColaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbtnEncolar = new javax.swing.JRadioButton();
        rbtnDesencolar = new javax.swing.JRadioButton();
        rbtnDesencolarCualquiera = new javax.swing.JRadioButton();
        rbtnVaciar = new javax.swing.JRadioButton();
        rbtnTamanioCola = new javax.swing.JRadioButton();
        rbtnCabeza = new javax.swing.JRadioButton();
        rbtnCola = new javax.swing.JRadioButton();
        rbtnMostrarCola = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtDatosCola = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDatoEncolar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDatoDesencolar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cola");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cola");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione una operación:");

        rbtnEncolar.setBackground(new java.awt.Color(51, 51, 51));
        rbtnEncolar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnEncolar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEncolar.setText("Encolar");
        rbtnEncolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEncolarActionPerformed(evt);
            }
        });

        rbtnDesencolar.setBackground(new java.awt.Color(51, 51, 51));
        rbtnDesencolar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnDesencolar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDesencolar.setText("Desencolar");
        rbtnDesencolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDesencolarActionPerformed(evt);
            }
        });

        rbtnDesencolarCualquiera.setBackground(new java.awt.Color(51, 51, 51));
        rbtnDesencolarCualquiera.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnDesencolarCualquiera.setForeground(new java.awt.Color(255, 255, 255));
        rbtnDesencolarCualquiera.setText("Desencolar cualquiera");
        rbtnDesencolarCualquiera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDesencolarCualquieraActionPerformed(evt);
            }
        });

        rbtnVaciar.setBackground(new java.awt.Color(51, 51, 51));
        rbtnVaciar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnVaciar.setForeground(new java.awt.Color(255, 255, 255));
        rbtnVaciar.setText("Vaciar cola");
        rbtnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVaciarActionPerformed(evt);
            }
        });

        rbtnTamanioCola.setBackground(new java.awt.Color(51, 51, 51));
        rbtnTamanioCola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnTamanioCola.setForeground(new java.awt.Color(255, 255, 255));
        rbtnTamanioCola.setText("Tamaño de la cola");
        rbtnTamanioCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTamanioColaActionPerformed(evt);
            }
        });

        rbtnCabeza.setBackground(new java.awt.Color(51, 51, 51));
        rbtnCabeza.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnCabeza.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCabeza.setText("¿Cuál es la cabeza de la cola?");
        rbtnCabeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCabezaActionPerformed(evt);
            }
        });

        rbtnCola.setBackground(new java.awt.Color(51, 51, 51));
        rbtnCola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnCola.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCola.setText("¿Cuál es la cola de la cola?");
        rbtnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnColaActionPerformed(evt);
            }
        });

        rbtnMostrarCola.setBackground(new java.awt.Color(51, 51, 51));
        rbtnMostrarCola.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        rbtnMostrarCola.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMostrarCola.setText("Mostrar cola");
        rbtnMostrarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMostrarColaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        txtDatosCola.setBackground(new java.awt.Color(204, 102, 0));
        txtDatosCola.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtDatosCola.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDatosCola, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDatosCola)
                .addContainerGap())
        );

        btnEjecutar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escriba aquí un dato:");

        txtDatoEncolar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("El dato debe ir ligado con la operación encolar.");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dato a desencolar:");

        txtDatoDesencolar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Este dato define el límite de desencolamiento.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnEncolar)
                    .addComponent(jLabel2)
                    .addComponent(rbtnDesencolar)
                    .addComponent(rbtnDesencolarCualquiera)
                    .addComponent(rbtnVaciar)
                    .addComponent(rbtnTamanioCola)
                    .addComponent(rbtnCabeza)
                    .addComponent(rbtnCola)
                    .addComponent(rbtnMostrarCola)
                    .addComponent(btnEjecutar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(284, 284, 284))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDatoDesencolar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDatoEncolar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnEncolar)
                    .addComponent(jLabel3)
                    .addComponent(txtDatoEncolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDesencolar)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnDesencolarCualquiera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnVaciar)
                    .addComponent(jLabel4)
                    .addComponent(txtDatoDesencolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTamanioCola)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnCabeza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnMostrarCola)
                        .addGap(11, 11, 11)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void rbtnMostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMostrarColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMostrarColaActionPerformed

    private void rbtnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnColaActionPerformed

    private void rbtnCabezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCabezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCabezaActionPerformed

    private void rbtnTamanioColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTamanioColaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTamanioColaActionPerformed

    private void rbtnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVaciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnVaciarActionPerformed

    private void rbtnDesencolarCualquieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDesencolarCualquieraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDesencolarCualquieraActionPerformed

    private void rbtnDesencolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDesencolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDesencolarActionPerformed

    private void rbtnEncolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEncolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEncolarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton rbtnCabeza;
    public javax.swing.JRadioButton rbtnCola;
    public javax.swing.JRadioButton rbtnDesencolar;
    public javax.swing.JRadioButton rbtnDesencolarCualquiera;
    public javax.swing.JRadioButton rbtnEncolar;
    public javax.swing.JRadioButton rbtnMostrarCola;
    public javax.swing.JRadioButton rbtnTamanioCola;
    public javax.swing.JRadioButton rbtnVaciar;
    public javax.swing.JTextField txtDatoDesencolar;
    public javax.swing.JTextField txtDatoEncolar;
    public javax.swing.JTextField txtDatosCola;
    // End of variables declaration//GEN-END:variables
}
