/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author kevin
 */
public class PanelControl extends javax.swing.JFrame {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUnidad1 = new javax.swing.JMenu();
        menuItemIterativos = new javax.swing.JMenuItem();
        menuItemRecursivos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemListaEnlazada = new javax.swing.JMenuItem();
        menuItemListaEnlazadaBD = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Control");
        setBackground(new java.awt.Color(0, 51, 255));
        setResizable(false);

        dpEscritorio.setBackground(new java.awt.Color(255, 204, 0));
        dpEscritorio.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Estructura de Datos");

        dpEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpEscritorioLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(172, 172, 172))
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpEscritorioLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        menuUnidad1.setText("Unidad 1");
        menuUnidad1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        menuItemIterativos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuItemIterativos.setText("Ejercicios iterativos");
        menuItemIterativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIterativosActionPerformed(evt);
            }
        });
        menuUnidad1.add(menuItemIterativos);

        menuItemRecursivos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuItemRecursivos.setText("Ejercicios recursivos");
        menuItemRecursivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRecursivosActionPerformed(evt);
            }
        });
        menuUnidad1.add(menuItemRecursivos);

        jMenuBar1.add(menuUnidad1);

        jMenu2.setText("Unidad 2");
        jMenu2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        menuItemListaEnlazada.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuItemListaEnlazada.setText("Listas enlazadas");
        jMenu2.add(menuItemListaEnlazada);

        menuItemListaEnlazadaBD.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuItemListaEnlazadaBD.setText("Lista enlazada - BD");
        menuItemListaEnlazadaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaEnlazadaBDActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemListaEnlazadaBD);

        jMenuBar1.add(jMenu2);

        menuSalir.setText("Salir");
        menuSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        menuItemSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(menuItemSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemIterativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIterativosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemIterativosActionPerformed

    private void menuItemRecursivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRecursivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRecursivosActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemListaEnlazadaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaEnlazadaBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListaEnlazadaBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem menuItemIterativos;
    public javax.swing.JMenuItem menuItemListaEnlazada;
    public javax.swing.JMenuItem menuItemListaEnlazadaBD;
    public javax.swing.JMenuItem menuItemRecursivos;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JMenu menuSalir;
    public javax.swing.JMenu menuUnidad1;
    // End of variables declaration//GEN-END:variables
}
