/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author kevin
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        dpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemMenuUsuario = new javax.swing.JMenuItem();
        itemMenuSalir = new javax.swing.JMenuItem();
        menuSecciones = new javax.swing.JMenu();
        itemMenuProfesores = new javax.swing.JMenuItem();
        itemMenuEstudiantes = new javax.swing.JMenuItem();
        itemMenuCursos = new javax.swing.JMenuItem();
        itemMenuMatricularAlumnos = new javax.swing.JMenuItem();
        menuDatabase = new javax.swing.JMenu();
        itemMenuBackup = new javax.swing.JMenuItem();
        itemMenuRestore = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UTI Education System");

        dpEscritorio.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archivero.png"))); // NOI18N
        menuArchivo.setText("File");
        menuArchivo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        itemMenuUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/changeUser.png"))); // NOI18N
        itemMenuUsuario.setText("Users");
        itemMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuUsuarioActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuUsuario);

        itemMenuSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        itemMenuSalir.setText("Log out");
        itemMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuSalir);

        jMenuBar1.add(menuArchivo);

        menuSecciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/secciones.png"))); // NOI18N
        menuSecciones.setText("Sections");
        menuSecciones.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        itemMenuProfesores.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N
        itemMenuProfesores.setText("Professors");
        menuSecciones.add(itemMenuProfesores);

        itemMenuEstudiantes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student.png"))); // NOI18N
        itemMenuEstudiantes.setText("Students");
        menuSecciones.add(itemMenuEstudiantes);

        itemMenuCursos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/online-course.png"))); // NOI18N
        itemMenuCursos.setText("Courses");
        menuSecciones.add(itemMenuCursos);

        itemMenuMatricularAlumnos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuMatricularAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enrollment.png"))); // NOI18N
        itemMenuMatricularAlumnos.setText("Enroll Students");
        menuSecciones.add(itemMenuMatricularAlumnos);

        jMenuBar1.add(menuSecciones);

        menuDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bd.png"))); // NOI18N
        menuDatabase.setText("Database");
        menuDatabase.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        itemMenuBackup.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backup.png"))); // NOI18N
        itemMenuBackup.setText("Backup");
        menuDatabase.add(itemMenuBackup);

        itemMenuRestore.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        itemMenuRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restore.png"))); // NOI18N
        itemMenuRestore.setText("Restore");
        menuDatabase.add(itemMenuRestore);

        jMenuBar1.add(menuDatabase);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuUsuarioActionPerformed

    private void itemMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dpEscritorio;
    public javax.swing.JMenuItem itemMenuBackup;
    public javax.swing.JMenuItem itemMenuCursos;
    public javax.swing.JMenuItem itemMenuEstudiantes;
    public javax.swing.JMenuItem itemMenuMatricularAlumnos;
    public javax.swing.JMenuItem itemMenuProfesores;
    public javax.swing.JMenuItem itemMenuRestore;
    public javax.swing.JMenuItem itemMenuSalir;
    public javax.swing.JMenuItem itemMenuUsuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenu menuArchivo;
    public javax.swing.JMenu menuDatabase;
    public javax.swing.JMenu menuSecciones;
    // End of variables declaration//GEN-END:variables
}
