/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author kevin
 */
public class MatricularAlumnosForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form MatricularAlumnosForm
     */
    public MatricularAlumnosForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtIdCursoMatricular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombreCursoMatricular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNombreProfesorCursoMatricular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIdEstudianteCursoMatricular = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnHabilitarCamposAlumnosMatriculados = new javax.swing.JButton();
        btnNuevoAlumnoMatriculado = new javax.swing.JButton();
        btnGuardarAlumnoMatriculado = new javax.swing.JButton();
        btnEliminarAlumnoMatriculado = new javax.swing.JButton();
        btnBuscarAlumnoMatriculado = new javax.swing.JButton();
        btnLimpiarCamposAlumnosMatriculados = new javax.swing.JButton();
        txtNombreAlumnoMatricular = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Enroll Students");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Id course:");

        txtIdCursoMatricular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtIdCursoMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCursoMatricularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Course Name:");

        txtNombreCursoMatricular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNombreCursoMatricular.setEnabled(false);
        txtNombreCursoMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoMatricularActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("Teacher Name:");

        txtNombreProfesorCursoMatricular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNombreProfesorCursoMatricular.setEnabled(false);
        txtNombreProfesorCursoMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfesorCursoMatricularActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setText("Id student:");

        txtIdEstudianteCursoMatricular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtIdEstudianteCursoMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEstudianteCursoMatricularActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setText("Student Name:");

        btnHabilitarCamposAlumnosMatriculados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/habilitar.png"))); // NOI18N
        btnHabilitarCamposAlumnosMatriculados.setToolTipText("Enable fields");

        btnNuevoAlumnoMatriculado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new user.png"))); // NOI18N
        btnNuevoAlumnoMatriculado.setToolTipText("New enroll student");

        btnGuardarAlumnoMatriculado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savechanges.png"))); // NOI18N
        btnGuardarAlumnoMatriculado.setToolTipText("Save enroll student");

        btnEliminarAlumnoMatriculado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnEliminarAlumnoMatriculado.setToolTipText("Delete enroll student");

        btnBuscarAlumnoMatriculado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarAlumnoMatriculado.setToolTipText("Search enroll student");

        btnLimpiarCamposAlumnosMatriculados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clean.png"))); // NOI18N
        btnLimpiarCamposAlumnosMatriculados.setToolTipText("Clean fields");

        txtNombreAlumnoMatricular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtNombreAlumnoMatricular.setEnabled(false);
        txtNombreAlumnoMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCursoMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtIdEstudianteCursoMatricular)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnNuevoAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnGuardarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarCamposAlumnosMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHabilitarCamposAlumnosMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreAlumnoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreProfesorCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdEstudianteCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombreAlumnoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreProfesorCursoMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevoAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumnoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarCamposAlumnosMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHabilitarCamposAlumnosMatriculados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCursoMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCursoMatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCursoMatricularActionPerformed

    private void txtNombreCursoMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoMatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoMatricularActionPerformed

    private void txtNombreProfesorCursoMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfesorCursoMatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesorCursoMatricularActionPerformed

    private void txtIdEstudianteCursoMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEstudianteCursoMatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEstudianteCursoMatricularActionPerformed

    private void txtNombreAlumnoMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoMatricularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoMatricularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarAlumnoMatriculado;
    public javax.swing.JButton btnEliminarAlumnoMatriculado;
    public javax.swing.JButton btnGuardarAlumnoMatriculado;
    public javax.swing.JButton btnHabilitarCamposAlumnosMatriculados;
    public javax.swing.JButton btnLimpiarCamposAlumnosMatriculados;
    public javax.swing.JButton btnNuevoAlumnoMatriculado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txtIdCursoMatricular;
    public javax.swing.JTextField txtIdEstudianteCursoMatricular;
    public javax.swing.JTextField txtNombreAlumnoMatricular;
    public javax.swing.JTextField txtNombreCursoMatricular;
    public javax.swing.JTextField txtNombreProfesorCursoMatricular;
    // End of variables declaration//GEN-END:variables
}
